### ISSUE TITLE
2 more issues

### ISSUE THREAD

**Issue by Lgk2** [furiouspuppy/Dota2_Bots#7] opened 2017-01-21 15:01 UTC
1: Meepo tries to farm the jungle with poof but for some reason he runs past the camp before he made sure to clear it (usually no monsters die at all and he simply wasted some mana). For some reason the issue doesn't occur at one of the camps but he usually ends up idling there for around 20 seconds every time he tries to farm the jungle. I only tested with the dire side so hopefully the bug is only happening there.

![meepo afk](https://cloud.githubusercontent.com/assets/7945495/22175323/ed03248a-dff2-11e6-8f0a-766bd01e8780.png)
![meepo still afk](https://cloud.githubusercontent.com/assets/7945495/22175324/ed232c3a-dff2-11e6-9318-6821576cfaf0.png)

2: It seems like most if not all of the heroes have trouble with investing points into talents.

**Comment by furiouspuppy** [comment] 2017-01-21 16:38
I haven't ever seen this happen, it sounds like he is trying to stack a neutral camp that is empty, but the timer in your pics clearly show its not stack time.  Hopefully the workshop update will fix it, meepos farm code had some revisions since the last update.  I'll keep an eye on it. 

Also for 2 the default bots don't use talents.  I need someone to go through and make builds for the default bots that use the talents and better item builds.  Its very easy if you look at meepo/puck item builds you'll see how its done I just haven't had the time yet.

**Comment by furiouspuppy** [comment] 2017-01-28 19:09
I finally went through and wrote builds for all 39 default bots that use talents and better item builds.  I'm going to close this one cause I still cant reproduce the first meepo error, but I am always refining his code so it may be gone or I may see it again.

**Closed as completed by furiouspuppy** 2017-01-28 19:09 UTC
